version: 2
updates:
  - package-ecosystem: docker
    directory: /ubuntu
    schedule:
      interval: daily
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: daily
    groups:
      pre-commit:
        patterns:
          - "*"
