name: Docker Build and Test

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  build-and-test-ubuntu-docker-image:
    name: Build and Test
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Docker Buildx
      # https://github.com/marketplace/actions/docker-setup-buildx

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      # Docker Login
      # https://github.com/marketplace/actions/docker-login

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and Test Docker images
      # https://github.com/marketplace/actions/build-and-push-docker-images

      - name: Build Ubuntu Docker Image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: ubuntu
          tags: |
            ghcr.io/osinfra-io/ubuntu:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Test Ubuntu Docker Image
        run: |
          docker run --rm ghcr.io/osinfra-io/ubuntu:test zsh --version
          docker run --rm ghcr.io/osinfra-io/ubuntu:test gcloud --version
          docker run --rm ghcr.io/osinfra-io/ubuntu:test brew --version
          docker run --rm ghcr.io/osinfra-io/ubuntu:test tofu --version
          docker run --rm ghcr.io/osinfra-io/ubuntu:test helm version
          docker run --rm ghcr.io/osinfra-io/ubuntu:test kubectl version --client
          docker run --rm ghcr.io/osinfra-io/ubuntu:test gh --version
